from .avatar import *
from .ghostping import *
from .help import *
from .nickname import *
from .ping_on_join import *
from .setprefix import *
from .other import *
from .roulette import *
from .kick import *
from .kroky import *
from .jaki_decki import *
from .clear import *
from .ban import *
from .cool_people import *
from .fun import *
from .colors import *
from .mute import *
from .emma import *
from .about import *
from .disconnect import *
from .math import *
from .emoji import *
from .info import *
from .editsnipe import *